### ISSUE TITLE
layout for cards

### ISSUE THREAD

**Issue by deepakydv9315** [plmdie/landing-page#1]
There is space between 2 cards which looks too odd,  you can use flex-wrap to fix or **you can add one more card**
![image](https://user-images.githubusercontent.com/76609302/161614597-f3583167-4756-4d25-813c-08bdfd603a7c.png)

**Comment by plmdie** [comment]
Hi, i'm a complete newbie trying to make this landing page, i already use flex-wrap.
Don't know how to fix it.

**Comment by plmdie** [comment]
Now it's centered, thanks!

**Comment by deepakydv9315** [comment]
I am also newbie that's why i am just trying to learn from others. nice to talk you bro:)

**Comment by plmdie** [comment]
Indeed, do you have a place to talk?

**Comment by deepakydv9315** [comment]
we can talk here : https://www.instagram.com/syco_coders/
